services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/TEAM-PYRO-BOTZ/PYRO-RENAME-BOT.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNELS
        sync: false
      - key: ADMINS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: PICS
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: COLLECTION_NAME
        sync: false
